### ISSUE TITLE
How to train the basline?

### ISSUE THREAD

**Issue by wwwmj23** [Kaiseem/SLAug#3]
Hi,
Thanks for your great work!
I have a question,how to train the basline?

**Comment by Kaiseem** [comment]
Hey,
You can turn off location_scale and saliency_balancing_fusion in the comfig/config.yaml by setting them false. Then, you can train the baseline model with the modified config files.

**Comment by wwwmj23** [comment]
> 

Thank you very much for your prompt reply. I have been trained according to what you said with one 3090, but it is quite different from the article. I trained the Abdominal CT->MRI dataset and the average result is 73.400 and the article was 77.31. Is that reasonable? This is my yaml file.
![image](https://github.com/Kaiseem/SLAug/assets/56493902/ccc6e639-d442-4aea-a94f-8255638ad5a2)

**Comment by Kaiseem** [comment]
Hi, the resutls on source-only are copied from our baseline [CSDG](https://github.com/cheng-01037/Causality-Medical-Image-Domain-Generalization). Compared with CSDG, there are two minor differences, i.e., in_channels (1 v.s. 3) and batch_size (32 v.s. 20). Nonetheless, we also cannot reproduce the results of source-only reported in CSDG. You can try it with CSDG source code. GOOD LUCK!
