### ISSUE TITLE
Incorrect Usage of 'mean' Instead of 'std' in vol_info Dictionary

### ISSUE THREAD

**Issue by Pluto-Ali** [Kaiseem/SLAug#4]
In CardiacDataset.py and AbdominalDataset.py, if self.normalize_op.mean is not None:    vol_info={'vol_vmin':img.min(),'vol_vmax':img.max(),'vol_mean':self.normalize_op.mean,'vol_std':self.normalize_op.mean} # Incorrect, should be 'std'

**Comment by Kaiseem** [comment]
thanks for pointing out the bug, you are right
